"""esquema inicial0

Revision ID: 38241ae2061c
Revises: 
Create Date: 2026-06-20 18:29:37.708885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38241ae2061c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('no_cliente', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('colonia', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('ref_nombre', sa.String(), nullable=False),
    sa.Column('ref_colonia', sa.String(), nullable=False),
    sa.Column('ref_telefono', sa.String(), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('estatus', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_index(op.f('ix_clientes_id_cliente'), 'clientes', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_clientes_no_cliente'), 'clientes', ['no_cliente'], unique=True)
    op.create_table('inventario',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('estilo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('talla', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.Enum('disponible', 'vendido', 'disponible_descuento', 'en_ruta', name='estatusinventario'), nullable=False),
    sa.Column('change_status', sa.DateTime(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_inventario_id_producto'), 'inventario', ['id_producto'], unique=False)
    op.create_table('movimientos',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('operacion', sa.Enum('contado', 'apartado', 'abono', 'gasto', name='operacion'), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('forma_pago', sa.Enum('efectivo', 'transferencia', 'tarjeta', name='formapago'), nullable=False),
    sa.Column('saldo_resultante', sa.Float(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['inventario.id_producto'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_index(op.f('ix_movimientos_id_movimiento'), 'movimientos', ['id_movimiento'], unique=False)
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(), nullable=False),
    sa.Column('id_producto_externo', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('talla', sa.String(), nullable=True),
    sa.Column('opcion_producto', sa.String(), nullable=True),
    sa.Column('opcion_marca', sa.String(), nullable=True),
    sa.Column('opcion_talla', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_index(op.f('ix_pedidos_id_pedido'), 'pedidos', ['id_pedido'], unique=False)
    op.create_table('pedidos_shein',
    sa.Column('id_pedido_shein', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_pedido_shein')
    )
    op.create_index(op.f('ix_pedidos_shein_id_pedido_shein'), 'pedidos_shein', ['id_pedido_shein'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_shein_id_pedido_shein'), table_name='pedidos_shein')
    op.drop_table('pedidos_shein')
    op.drop_index(op.f('ix_pedidos_id_pedido'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_movimientos_id_movimiento'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_inventario_id_producto'), table_name='inventario')
    op.drop_table('inventario')
    op.drop_index(op.f('ix_clientes_no_cliente'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id_cliente'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
